#!/usr/bin/env zsh
# Set a visual indicator of vi mode

cursor_mode() {
  cursor_block='\e[2 q'
  cursor_beam='\e[6 q'

  function zle-keymap-select {
    case $KEYMAP in
      vicmd) echo -ne "$cursor_block";;
      main|viins) echo -ne "$cursor_beam";;
    esac
  }

  zle-line-init() {
    echo -ne "$cursor_beam"
  }

  zle -N zle-keymap-select
  zle -N zle-line-init
}

cursor_mode
