#!/usr/bin/env zsh

export DOTFILES="${HOME}/.dotfiles"

# XDG
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${XDG_CONFIG_HOME}/local/share"
export XDG_CACHE_HOME="${XDG_CONFIG_HOME}/cache"

# Editor
export EDITOR='nvim'
export VISUAL='nvim'

# zsh
ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

